version: '3.4'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_ROOT=/app
    volumes:
      - $PWD:/app
  streamlit:
    profiles:
      - donotstart
    build: .
    command: python -m streamlit run streamlit_app.py
    ports:
      - "8501:8501"
    environment:
      - DATABASE_ROOT=/app
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.credentials/prosper-mlops-poc-8d987c9a4207.json
    volumes:
      - $PWD:/app
  nuclio:
    image: quay.io/nuclio/dashboard:stable-amd64
    ports:
      - "8070:8070"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp